<div id="centercol">
	<div id="products-all">
		<div id="display">
			<div class="product">
				<p class="product-title-main">
					Cartelas
				</p>
				<img src="/cartons/cartelas/thumbs/<?=$this->sampleImage;?>.jpg"
					alt="Exemplo Cartela" />
					
				<div class="barra-botoes-main">
					<button class="button"
						onclick='window.location="caixas/cartelas"'>Entrar</button>

				</div>
			</div>
		</div>
	</div>
</div>