<div class="row">
	<div class="col-sm-12">
		<h3 class="header smaller lighter green">
			<i class="ace-icon fa fa-list-alt"></i>
			Listagem Cortantes
			<button type="button" class="close" id="diecuts_dismiss_new" onclick="dismissDiecutForm()">
				<i class="ace-icon fa fa-times"></i>
			</button>
		</h3>

	</div>

	<div class="col-sm-12">

		<table class="table table-bordered table-striped table-hover table-condensed table-responsive">
			<thead>
			<tr>
				<th>Estante</th>
				<th>C&oacute;d.</th>
				<th>Cortante</th>
				<th style="text-align:center;">A</th>
				<th style="text-align:center;">B</th>
				<th style="text-align:center;">H</th>
				<th style="text-align:center;">f</th>
				<th style="text-align:center;">g</th>
				<th style="text-align:center;">Fto Std</th>
				<th style="text-align:center;">Editar</th>
			</tr>
			</thead>
			<tbody>
			<?php foreach ($this->results as $name) : ?>
			<tr id="diecut-<?=$name['id']?>">
				<td align="center"><?=$name['estante'];?></td>
				<td><?=str_replace(" ", "", $name['codigo']);?></td>
				<td id="diecutNumber-<?=$name['id'];?>">
					<div class="btn-group">
						<button data-toggle="dropdown" class="btn btn-xs btn-info btn-white dropdown-toggle" aria-expanded="false">
							<?=$name['cortante'];?>
							<span class="ace-icon fa fa-caret-down icon-only"></span>
						</button>

						<ul class="dropdown-menu dropdown-info dropdown-menu-right">
							<li>
								<a href="#" onclick='addDiecutToOptimus("<?=$name['id'];?>","<?=$name['cortante']?>")'><i class="ace-icon fa fa-upload"></i> Inserir Cortante no Optimus</a>
							</li>

							<li>
								<a href="#" onclick='removeDiecutFormOptimus("<?=$name['id'];?>")'><i class="ace-icon fa fa-times"></i> Remover Cortante do Optimus</a>
							</li>
						</ul>
					</div>
					<?php if (!empty($name['alteracoes'])):?>
						<span class="label label-warning pull-right">
							<i class="ace-icon fa fa-exclamation-triangle bigger-120"></i>
							 &nbsp;Cortante com alterações
						</span>
					<?endif; ?>
					<span id="diecutsToOptimus-<?=$name['id']?>"></span>
				</td>
				<td align="center"><?=$name['A'];?></td>
				<td align="center"><?=$name['B'];?></td>
				<td align="center"><?=$name['H'];?></td>
				<td align="center"><?=$name['f'];?></td>
				<td align="center"><?=round($name['g'], 2);?></td>
				<td align="center"><?=$name['formato_std'];?></td>
				<td align="center" id="diecut-edit-<?=$name['id']?>">
					<i class="ace-icon fa fa-edit bigger-120" style="cursor: pointer;" onclick="populateDiecut('<?=$name['id']?>', 'diecut-<?=$name['id']?>')"></i>
				</td>
				<?php endforeach; ?>
			</tr>
			</tbody>
		</table>

	</div>
</div>

