<?php
$this->placeholder('js')->set('
<script src="/js/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="/js/jquery.easing.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery-ui-1.7.2.custom.min.js"></script>
<link type="text/css" href="/css/redmond/jquery-ui-1.7.2.custom.css" rel="stylesheet" />
' . App_Javascript_Date_Helper::generateSingleDatePickers('data_entrega'));

?>

<div id="cont">
<fieldset><legend>Editar Registo</legend>
<?=$this->form->render();?>
</fieldset>
</div>
<script type="text/javascript">
<!--
$(function() {$("input:submit").button();});
//-->
</script>
