<div id="primarycontainer">
<div id="primarycontent">
<?php
if ($this->errors) {
    $newmsg = new App_Messages();
    $newmsg->setMessageType('error');
    $newmsg->setMessage('Ocorreu um erro. O formul&aacute;rio n&atilde;o est&aacute; bem preenchido.');
    echo $newmsg->displayMessage();
    echo '<div id="cont">
    <fieldset><legend>Editar Registo</legend>';
    echo $this->form->render();
    echo'</fieldset>
    </div>';
} else {
    $newmsg = new App_Messages();
    $newmsg->setMessageType('success');
    $newmsg->setMessage('O registo foi actualizado com sucesso.');
    echo $newmsg->displayMessage();
}
?>

</div>
</div>
<script type="text/javascript">
<!--
$(function() {$("input:submit").button();});
//-->
</script>