

<div class="row">

	<div class="col-sm-1 col-sm-offset-2">
		<a href="/selo" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-list-alt bigger-230"></i>
	Selo

		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="<?=$this->navigation()->findBy('id', "braille")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-language bigger-230"></i>
		Braille

		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="<?=$this->navigation()->findBy('id', "arqbraille_listagem")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-th bigger-230"></i>
		Arq Brailles

		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="<?=$this->navigation()->findBy('id', "codigolaetus")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-align-justify bigger-230 fa-rotate-90"></i>
		Laetus
		</a>
	</div>

</div>
<div class="row">

	<div class="col-sm-1 col-sm-offset-2">
		<a href="<?=$this->navigation()->findBy('id', "diecuts")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-square-o bigger-230"></i>
			Cortantes
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/cockpit" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-table bigger-230"></i>
			Obras
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/tolerancias" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-file-text-o bigger-230"></i>
			Tolêrancias
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/labs" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-hdd-o bigger-230"></i>
			Registos
		</a>
	</div>

</div>
<div class="row">

	<div class="col-sm-1 col-sm-offset-2">
		<a href="<?=$this->navigation()->findBy('id', "arquivochapas")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-inbox bigger-230"></i>
			Arq Chapas
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="<?=$this->navigation()->findBy('id', "chapasrecuperadas")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-recycle bigger-230"></i>
			Chapas Rec
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/labshome" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-flask bigger-230"></i>
			Labs
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/cliches" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-picture-o bigger-230"></i>
			Clichés
		</a>
	</div>

</div>
<div class="row">

	<div class="col-sm-1 col-sm-offset-2">
		<a href="/producao" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-dashboard bigger-230"></i>
			Produção
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="/entregas" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-truck bigger-230"></i>
			Entregas
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">
		<a href="<?=$this->navigation()->findBy('id', "config")->get("uri");?>" class="btn btn-default btn-app radius-4">
			<i class="ace-icon fa fa-cogs bigger-230"></i>
			Config
		</a>
	</div>
	<div class="col-sm-1 col-sm-offset-1">

	</div>

</div>