<div id="dameespaco">
<table><tr><td>
<a href="/arqchapas/new" id="new-arqchapas">+ criar novo registo</a>
</td><td class="esp"></td><td>
<form action="/arqchapas/search" method="post">Insira o C&oacute;digo F3:&nbsp;
<input type="text" size="15" id="codf3" name="codf3"></input> <input
	type="submit" value="Procurar"></input></form></td>
	</tr></table>
</div>
<table class="bordered">
	<tr>
		<!-- <th>ID</th> -->
		<th>C&oacute;digo F3</th>
		<th>Cortante</th>
		<th>Vers&atilde;o</th>
		<th>Produto</th>
		<th>700x1000</th>
		<th>1000x700</th>
		<th>800x700</th>
		<th>700x800</th>
		<th>000x000</th>
		<th>550x800</th>
		<th>698x498</th>
		<th>698x398</th>
		<th>698x332</th>
		<th>Tipo</th>
		<th>Caixa N&ordm;</th>
	</tr>
  
<?php

$i = 1;
$color = new App_Styles_RowColor();
$color->setColors('white', 'alt');


foreach ($this->paginator as $record) {
    echo '<tr class="' . $color->display($i) . '">';
    echo '<td class="spec" align="center"><a href="/arqchapas/editrecord/'.$record['codf3'].'">' . $record['codf3'] . '</a></td>';
    echo '<td>' . $record['cortante'] . '</td>';
    echo '<td>' . $record['versao'] . '</td>';
    echo '<td>' . $record['produto'] . '</td>';
    echo '<td>' . $record['700_1000'] . '</td>';
    echo '<td>' . $record['1000_700'] . '</td>';
    echo '<td>' . $record['800_700'] . '</td>';
    echo '<td>' . $record['700_800'] . '</td>';
    echo '<td>' . $record['000_000'] . '</td>';
    echo '<td>' . $record['550_800'] . '</td>';
    echo '<td>' . $record['698_498'] . '</td>';
    echo '<td>' . $record['698_398'] . '</td>';
    echo '<td>' . $record['698_332'] . '</td>';
    echo '<td>' . $record['tipo'] . '</td>';
    echo '<td align="center">' . $record['arquivo'] . '</td>';
    echo '</tr>';
    $i ++;
}
?>
</table>

<?='<p>' . $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') . '</p>';?>
<script>
$(function(){$("#new-arqchapas").button();});
</script>