<?=$this->partial('partials/searchemprova.phtml');?>
<?php 
$this->placeholder('scripts')->set('<script type="text/javascript">
<!--
$(function() {
    $("input:button, input:submit, a", ".sessao").button();
    $("a", ".sessao").click(function() { window.location="/emprova/new"; return false; });
	});
//-->
</script>');
?>

<br />
<div id="tabs">
<ul>
	<li><a href="#tabs-1">Provas Prepress - Dep Tec</a></li>
	<li><a href="#tabs-2">Provas em Produ&ccedil;&atilde;o</a></li>
</ul>

<div id="tabs-1">
<?php if (count($this->emprova) > 0 ) : ?>
<br />
<span class="sessao">
<a href="#">+ criar novo registo</a>
</span>
<div align="center" style="padding-top: 20px"><br />
<h4>Provas em Produ&ccedil;&atilde;o</h4>
<table class="bordered">
	<tr>
		<th>Reg.</th>
		<th>Laborat&oacute;rio</th>
		<th>Descri&ccedil;&atilde;o</th>
		<th>C&oacute;d. Produto</th>
		<th>In&iacute;cio</th>
		<th>PrePress</th>
		<th>Dep. Tec.</th>
	</tr>
<?php

$i = 1;
$color = new App_Styles_RowColor();
$color->setColors('white', 'alt');

foreach ($this->emprova as $name) :
$obras = $this->obras->getValues($name['obra']);
$optimus = $this->optimus->getJobData($name['obra']);

$dia = explode("-", $name['dia']);
$hora = explode(":", $name["hora"]);

$hoje  = mktime(date("G"), date("H"), date("i"), date("m"), date("d"), date("Y"));
$dataProva = mktime($hora[0], $hora[1], $hora[2], $dia[1] , $dia[2]+2, $dia[0]);



if ($hoje > $dataProva)
{
    $rowColor = 'orange';
    
} else {
    $rowColor = $color->display($i);
}

?>

<tr class="<?=$rowColor;?>">
		<?php if (count($obras) > 0 ) : ?>
		<td class="spec"><a href="/cockpit/preview/<?=$name['obra'];?>"><?=$name['obra'];?></a></td>
        <?php else: ?>
		<td class="specalt"><?=$name['obra'];?></td>
        <?php endif;?>
		<td><?=$optimus['j_customer'];?></td>
		<td><?=$optimus['j_title1'];?></td>
		<td><?=$optimus['j_title2'];?></td>
		<td><?=$name['dia'] ." " . $name['hora'];?></td>
		<?php if ($name['estado'] == 0):?>
		<td><a href="#" onClick="provaPrepress(<?=$name['id'];?>,<?=$name['obra'];?> );">Concluir</a></td>
		<?php else:?>
		<td class="tdgreen">Concluido</td>
		<?php endif;?>
		<td><a href="#" onClick="provaDepTec(<?=$name['id'];?>,<?=$name['obra'];?> );">Concluir</a></td>
<?php
    $i ++;
endforeach;
?>
</tr>
</table>
<p>
<?=$this->paginationControl($this->emprova, 'Sliding', 'paginationTabs1.phtml');?>
</p>	
</div>
<?php else:?>
<a href="/emprova/new">+ criar novo registo</a>
<div align="center" style="padding-top: 20px"><br />
<h4>N&atilde;o existem Provas em Produ&ccedil;&atilde;o</h4>
</div>
<?php endif;?>
</div>
<div id="tabs-2">
<?php if (count($this->emprovaOptimus) > 0 ) : ?>
<div align="center" style="padding-top: 20px"><br />
<h4>Provas em Produ&ccedil;&atilde;o</h4>
<table class="bordered">
	<tr>
		<th>Reg.</th>
		<th>Laborat&oacute;rio</th>
		<th>Descri&ccedil;&atilde;o</th>
		<th>C&oacute;d. Produto</th>
		<th>In&iacute;cio</th>
	</tr>
<?php
$i = 1;
$color = new App_Styles_RowColor();
$color->setColors('white', 'alt');	
foreach ($this->emprovaOptimus as $optimus) :
$obras = $this->obras->getValues($optimus['j_number']);?>
<tr class="<?=$color->display($i);?>">
		<?php if (count($obras) > 0 ) : ?>
		<td class="spec"><a href="/cockpit/preview/<?=$optimus['j_number'];?>"><?=$optimus['j_number'];?></a></td>
        <?php else: ?>
		<td class="specalt"><?=$optimus['j_number'];?></td>
        <?php endif;?>
		<td><?=$optimus['j_customer'];?></td>
		<td><?=$optimus['j_title1'];?></td>
		<td><?=$optimus['j_title2'];?></td>
		<td><?=$optimus['j_datein'];?></td>
		
		
		

<?php
    $i ++;
endforeach;
?>
</tr>
</table>
<p>
<?=$this->paginationControl($this->emprovaOptimus, 'Sliding', 'paginationTabs2.phtml');?>
</p>
<?php else:?>
<h2>N&atilde;o existem obras em Prova</h2>
<?php endif;?>
</div>
</div>
</div>
	