<?php Zend_Layout::getMvcInstance()->assign("jsqtip", TRUE);?>
<?php Zend_Layout::getMvcInstance()->assign("flag", TRUE);?>
<div class="page-header">
	<h1>
		Criar Braille

	</h1>
</div>

<div class="alert alert-danger" id="braille_index_error_alerts" style="display: none;">
	<button type="button" class="close" data-dismiss="alert">
		<i class="ace-icon fa fa-times"></i>
	</button>

	<strong>
		<i class="ace-icon fa fa-times"></i>

	</strong>

	<span id="errors"></span>
	<br>
</div>
<?= $this->form;?>
<script type="text/javascript" src="/js/jquery.form.js"></script>
