<?=$this->partial('partials/searchentregas.phtml');?>
<div align="center" style="padding-top: 20px"><br />
<br />
<h4>Resultados</h4>
<table class="bordered">
	<tr>
		<th>Reg</th>
		<th>Tipo Obra</th>
		<th>Cliente</th>
		<th>Descri&ccedil;&atilde;o</th>
		<th>C&oacute;digo</th>
		<th>OC</th>
		<th>Data<br />
		In&iacute;cio</th>
		<th>Data<br />
		Pedida</th>
		<th>Qtd<br />
		Pedida</th>
	</tr>
<?php
$i = 1;
$color = new App_Styles_RowColor();
$color->setColors('white', '#eff9fe');
foreach ($this->results as $name) :
    ?>
    
    
<tr bgcolor="<?=$color->display($i);?>">
		<td><a href="/cockpit/preview/<?=$name['j_number'];?>"><?=$name['j_number'];?></a></td>
		<td><?=App_Change::fundo($name['j_type']);?></td>
		<td><?=$name['j_customer'];?></td>
		<td><?=$name['j_title1'];?></td>
		<td><?=$name['j_title2'];?></td>
		<td><?=$name['j_ordnum'];?></td>
		<td><?=App_Change::date($name['j_datein']);?></td>
		<td><?=App_Change::date($name['j_deldate']);?></td>
		<td><?=$name['j_qty_ordered'];?></td>
</tr>
<?php
    $i ++;
endforeach;
?>

</table>
<p>
<?=$this->paginationControl($this->results, 'Sliding', 'pagination.phtml');?>
</p>
</div>