<div class="page-header">
	<ul class="list-unstyled list-inline">
		<li><h1>Alterar Braille Nº<?=$this->num;?></h1></li>
		<li><button type="button" class="btn btn-white btn-primary btn-sm"><a href="#modal-form-braille-repetitions" role="button" id="rep-ist" class="blue" data-toggle="modal" style="text-decoration: none;"> <i class="fa fa-cubes"></i>&nbsp;Repetição Peças </a></button></li>
		<!-- <li><button type="button" class="btn btn-white btn-primary btn-sm"><a href="#" id="rep-listagem"><i class="fa fa-file-text-o"></i>&nbsp;Listagem Repetição Peças</a></button></li> -->
	</ul>
</div>



<div class="col-xs-12 col-lg-6" style="border-right: 1px solid #e8e8e8;">

	<span id="loading-animation"></span>
	<form action="<?=$this->form->getAction() ?>" enctype="<?php echo $this->form->getEnctype() ?> "method="<?php echo $this->form->getMethod() ?>" id="<?php echo $this->form->getId() ?>" class="<?=$this->form->getAttrib("class")?>" role="form" horizontal="true">

			<?=$this->form->arqbraillegroup1;?>


			<?=$this->form->arqbraillegroup2;?>



		<div class="clearfix"><?=$this->form->arqbraillegroup3;?></div>

	</form>

</div>
<div class="col-xs-12 col-lg-6">
	<div id="braille_rept_div"></div>

</div>




<script type="text/javascript" src="/js/jquery.form.js"></script>

<div id="modal-form-braille-repetitions" class="modal" tabindex="-1" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h4 class="blue bigger"><i class="fa fa-edit"></i>&nbsp;Preencha o formulário</h4>
			</div>

			<div class="modal-body">
				<div id="alert"></div>
				<form id="rep-braille-form" action="/arqbraille/repcreate" method="post" class="form-horizontal" role="form">
					<div class="form-group">
						<label class="col-sm-3 control-label no-padding-right" for="nbraille_num_rep">Braille Nº:</label>
						<div class="col-sm-9">
							<input readonly type="text" class="form-control" placeholder="insira o número do braille" id="nbraille_num_rep" name="nbraille_num_rep"/>
						</div>
					</div>
					<div id="group-pecas">
						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" for="pecas_rep">Peças:</label>
							<div class="col-sm-9">
								<input type="text" class="form-control" placeholder="insira o nº de peças a repetir" id="pecas_rep" name="pecas_rep"/>
							</div>
						</div>
					</div>
					<div class="space-6"></div>
					<div><h4 class="header smaller lighter blue">Motivo:</h4></div>
					<div class="col-sm-3">

						<div class="form-group">
							<label>
								<input type="checkbox" name="oxidacao_rep" id="oxidacao_rep" class="ace" value="1"/>
								<span class="lbl">&nbsp;Oxidação</span>
							</label>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<label>
								<input type="checkbox" name="partidos_rep" id="partidos_rep" class="ace" value="1"/>
								<span class="lbl">&nbsp;Partidos</span>
							</label>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<label>
								<input type="checkbox" name="esmagados_rep" id="esmagados_rep" class="ace" value="1"/>
								<span class="lbl">&nbsp;Esmagados</span>
							</label>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="form-group">
							<label>
								<input type="checkbox" name="novo_rep" id="novo_rep" class="ace" value="1"/>
								<span class="lbl">&nbsp;Novo Cortante</span>
							</label>
						</div>
					</div>

				<h4 class="header smaller lighter blue">&nbsp;</h4>
			</div>
			<div class="space-4"></div>
			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					Cancel
				</button>

				<button class="btn btn-sm btn-primary">
					<i class="ace-icon fa fa-check"></i>
					Guardar
				</button>
			</div>
		</div>
		</form>
	</div>
</div>