<div class="page-header">
	<h1>
		Criar Laboratório para Arquivo de Brailles

	</h1>
</div>
<span id="errors"></span>

<div class="col-xs-12 col-lg-6">
	<h3><i class="ace-icon fa fa-edit"></i> Laboratório</h3>
<?=$this->form;?>
</div>

<div class="col-xs-12 col-lg-6"  style="border-left: 1px solid #e8e8e8;">
		<table class="table table-striped table-bordered table-hover" style="width: 50%" id="arqbraille-labs-table">
			<thead>
			<tr>
				<th>Nome Optimus</th>
				<th>Abreviatura</th>
				<th>Editar</th>
			</tr>
			</thead>
			<tbody class="small">
			<?php foreach ($this->labs as $lab) : ?>
				<tr id="<?=$lab['id']?>">
					<td id="lab-<?=$lab['id']?>"><?=$lab['optimus'];?></td>
					<td id="short-<?=$lab['id']?>"><?=$lab['shortname'];?></td>
					<td id="but-<?=$lab['id']?>">
						<div class="hidden-sm hidden-xs btn-group">
							<button class="btn btn-xs btn-info" onclick="editArqbrailleLabs('<?=$lab["id"]?>','<?=$lab['optimus'];?>')">
								<i class="ace-icon fa fa-pencil bigger-120"></i>
							</button>

							<button class="btn btn-xs btn-danger"  onclick="deleteArqBrailleLabs('<?=$lab["id"]?>')">
								<i class="ace-icon fa fa-trash-o bigger-120"></i>
							</button>
						</div>
						<div class="hidden-md hidden-lg">
							<div class="inline pos-rel">
								<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
									<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
								</button>

								<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
									<li>
										<a href="#" class="tooltip-success" data-rel="tooltip" title="" data-original-title="Edit">
											<span class="green"><i class="ace-icon fa fa-pencil-square-o bigger-120"></i></span>
										</a>
									</li>
									<li>
										<a href="#" class="tooltip-error" data-rel="tooltip" title="" data-original-title="Delete">
											<span class="red"><i class="ace-icon fa fa-trash-o bigger-120"></i></span>
										</a>
									</li>
								</ul>
							</div>
						</div>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
</div>
<div id="arqbraille-labs-aux" style="display: none;"></div>
