<div class="page-header">
	<h1>
		Novo Registo Arquivo de Brailles

	</h1>
</div>

<span id="loading-animation"></span>
<form action="<?=$this->form->getAction() ?>" enctype="<?php echo $this->form->getEnctype() ?> "method="<?php echo $this->form->getMethod() ?>" id="<?php echo $this->form->getId() ?>" class="<?=$this->form->getAttrib("class")?>" role="form" horizontal="true" onsubmit="return checknewbraille()">
<div class="col-xs-6">
	<?=$this->form->arqbraillegroup1;?>

</div>
<div class="col-xs-6">
	<?=$this->form->arqbraillegroup2;?>


</div>
	<div class="clearfix"><?=$this->form->arqbraillegroup3;?></div>

</form>





