<div class="page-header">
	<h1>Simular Preço Braille</h1>
</div>



<div class="col-xs-12 col-lg-6" style="border-right: 1px solid #e8e8e8;">

	<h3>Braille Macho</h3>
	<div id="validateformtext"></div>
	<?=$this->form?>

	<h3>Braille Fêmea</h3>
	<div id="validateformtextfemea"></div>
	<?=$this->formfemea?>

</div>




<div class="col-xs-12 col-lg-6">
	<div id="responseText"></div>

</div>




<script type="text/javascript" src="/js/jquery.form.js"></script>

 