<?php if ($this->errors) :?>


<div id="dameespaco"></div>
<div class="barra-brailles">
<table>
<tr>
    <td class="sessao dir-sp-10"><a href="/arqbraille">Listagem</a></td>
</tr>
</table>
</div>
<div id="primarycontainer">
	<div id="primarycontent">
	<div class="box">
<h3>Braille Selo</h3>
<span class="form"><span id="errors"></span>

<?=$this->form;?>
</span>
</div>
</div>
</div>
<script type="text/javascript">
$(function() {
    $("input:submit").button();
    $("#numbraille").focus();
    $("input:button, input:submit, a", ".sessao").button();
    
});
</script>

<?php else: 
header('Content-type: application/pdf');
echo $this->pdf->render();
?>

<?php endif;?>