<div class="row" id="message_new_chapas_recuperadas" style="display: none;">
	<div class="col-sm-6">
		<div id="diecuts_msg-flash" class="alert alert-block alert-success">
			<button type="button" class="close" data-dismiss="alert">
				<i class="ace-icon fa fa-times"></i>
			</button>
			<p>
				<strong><i class="ace-icon fa fa-check"></i></strong>
				Registo criado com sucesso.
			</p>
		</div>
	</div>
</div>




<div class="row">

	<div class="col-sm-6 col-sm-offset-1">

		<h3 class="row header smaller lighter blue"><i class="ace-icon fa fa-cog"></i> Novo Registo</h3>

		<?=$this->form->render()?>
	</div>

</div>