<?php
if ($this->errors) {
    echo '<div id="cont">';
    $error = new App_Messages();
    $error->setMessageType('error');
    $error->setMessage('Ocorreu um erro. Os dados n&atilde;o est&atilde;o correctos. Por favor tente de novo.');
    echo $error->displayMessage() . "<br /><br />";
    echo '<div id="cont"><fieldset><legend> Novo Registo</legend>';
    echo $this->form;
    echo '</fieldset></div>';
    echo '</div>';
} else {
    if ($this->flag == 1) {
        header('Content-type: application/pdf');
        echo $this->pdf
            ->render();
    } else {
        $this->placeholder('js')
            ->set('<script type="text/javascript" charset="utf-8">$(document).ready(function() {$("button, input:submit, a", ".check").button();});</script>');
        echo '<div id="cont"><table class="check"><tr><td><a href="/laetus">Criar Laetus</a></td><td><a href="/laetus/checklaetus">Verificar Laetus</a></td><td><a href="/laetus/recreatelaetus">Regenerar Laetus</a></td><td><a href="/laetus/editlaetusform">Editar Laetus</a></td></tr></table><br /><br />';
        $error = new App_Messages();
        $error->setMessageType('success');
        $error->setMessage('Os dados foram inseridos correctamente.');
        echo $error->displayMessage();
        echo '</div>';
    }
}

