<?php
if ($this->errors) {
    echo '<div id="cont">';
    $error = new App_Messages();
    $error->setMessageType('error');
    $error->setMessage('Ocorreu um erro. Os dados n&atilde;o est&atilde;o correctos. Por favor tente de novo.');
    echo $error->displayMessage() . "<br /><br />";
    echo '<div id="cont"><fieldset><legend>Editar C&oacute;digo Laetus</legend>';
    echo $this->form;
    echo '</fieldset></div>';
    echo '</div>';
} else {
$this->placeholder('js')->set('
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
$("button, input:submit, a", ".check").button();
});
</script>');
?>
<div id="cont">
<?=$this->partial('partials/laetusbotoes.phtml');?>
<?php
$error = new App_Messages();
$error->setMessageType('success');
$error->setMessage('O registo foi actualizado com sucesso');
echo $error->displayMessage();
?>
</div>
<?php }?>