<?php

/**
 * chapasrec
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6698 2009-11-10 17:58:02Z jwage $
 */
class chapasrec extends Basechapasrec
{

    public function getAllRecordsByDate ()
    {

        $q = Doctrine_Query::create();
        $q->select();
        $q->from('chapasrec c');
        $q->orderBy('c.dia DESC');
        return $q->fetchArray();
    }

    public function insertRecords ($obra, $cliente, $cores, $verniz, $data)
    {

        $this->obra = $obra;
        $this->cliente = $cliente;
        $this->cores = $cores;
        $this->verniz = $verniz;
        $this->dia = $data;
        $this->save();
    }

    public function updateRecord ($obra, $cliente, $cores, $verniz, $data)
    {

        $q = Doctrine_Query::create();
        $q->update('chapasrec')->set(array(
            'obra' => $obra , 
            'cliente' => $cliente , 
            'cores' => $cores , 
            'verniz' => $verniz , 
            'dia' => $data));
        $q->where('obra = ?', $obra);
        $q->execute();
    }

    public function getNumberOfPlates ()
    {

        $q = Doctrine_Query::create();
        $q->select('cores, verniz');
        $q->from('chapasrec');
        $q->where('dia LIKE ?', date(Zend_Date::YEAR_8601) . '%');
        $values = $q->execute();
        foreach ($values as $plates) {
            $allPlatesArray[] = $plates->cores + $plates->verniz;
        }
        $allPlates = array_sum($allPlatesArray);
        return $allPlates;
    }
    
    public function getNumberOfPlatesByYear ($year)
    {
    
        $q = Doctrine_Query::create();
        $q->select('cores, verniz');
        $q->from('chapasrec');
        $q->where('dia LIKE ?', date($year) . '%');
        $values = $q->execute();
        foreach ($values as $plates) {
            $allPlatesArray[] = $plates->cores + $plates->verniz;
        }
        $allPlates = array_sum($allPlatesArray);
        return $allPlates;
    }

    public function getRecordByJobNumber ($jobnumber)
    {

        $q = Doctrine_Query::create();
        $q->select();
        $q->from('chapasrec');
        $q->where('obra = ?', $jobnumber);
        return $q->fetchOne();
    }

    public function countRecords ($jobnumber)
    {

        $q = Doctrine_Query::create();
        $q->select();
        $q->from('chapasrec');
        $q->where('obra = ?', $jobnumber);
        return $q->count($q);
    }

    public function deleteRecord ($obra)
    {

        $q = Doctrine_Query::create();
        $q->delete('chapasrec');
        $q->where('obra = ?', $obra);
        $update = $q->execute();
    }
    
    public function getClients() 
    {
       $q = Doctrine_Query::create();
       $q->select();
       $q->from('chapasrec');
       $q->where('YEAR(dia) = ?', date(Zend_Date::YEAR_8601));
       $q->groupBy('cliente');
       return $q->fetchArray();
    }
    
    public function sumChapasByClient($client)
    {
        $q = Doctrine_Query::create();
        $q->select('SUM(cores) as cores,SUM(verniz) as verniz');
        $q->from('chapasrec');
        $q->where('cliente = ?', $client);
        $q->andWhere('YEAR(dia) = ?', date(Zend_Date::YEAR_8601));
        $all =  $q->fetchArray();
        
        /*foreach ($all as $value) {
            $sum = $value['cores'] + $value['verniz'];
        }*/
        
        return $all;
               
    }
}