<?php
$datepicker1 = App_Javascript_Date_Helper::generateSingleDatePickers('dataenvio');
$datepicker2 = App_Javascript_Date_Helper::generateSingleDatePickers('datapedida');
echo $datepicker1 . $datepicker2;

?>
<div id="cont">
<fieldset><legend>Editar Execução Cortante</legend>
<span id="errmsg" style="color: white;background-color: red;width: 50px;height: 20px;padding: 5px;display: none;margin-bottom: 8px;"></span>
<br />
<?=$this->form->render();?>
</fieldset>
</div>
<script type="text/javascript">
$(document).ready(function() {
	
	$( "#abh-a" ).val(<?=$this->formValues['a'];?>);
	$( "#abh-b" ).val(<?=$this->formValues['b'];?>);
	$( "#abh-h" ).val(<?=$this->formValues['h'];?>);
	$( "#submit").val('Alterar Valores');
	$("button, input:submit").button();
});
</script>