<div id="modal-form-mail-pdf" class="modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h4 class="blue bigger">Please fill the following form fields</h4>
			</div>

			<div class="modal-body">
				<form action="/ajax/sendmailtosiopa" class="dropzone dz-clickable" id="my-awesome-dropzone" enctype="multipart/form-data">
					<div class="row">


						<div class="col-xs-12">
							<div class="form-group">



							</div>

							<div class="space-4"></div>

							<div class="form-group">
								<label for="form-field-username">Username</label>

								<div>
									<input class="input-large" type="text" id="form-field-username" placeholder="Username">
								</div>
							</div>

							<div class="space-4"></div>

							<div class="form-group">
								<label for="form-field-first">Name</label>

								<div>
									<input class="input-medium" type="text" id="form-field-first" placeholder="First Name">

								</div>
							</div>
						</div>
						<div class="dropzone-previews"></div>
					</div>
				</form>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					Cancel
				</button>

				<button class="btn btn-sm btn-primary" type="submit">
					<i class="ace-icon fa fa-check"></i>
					Enviar
				</button>
			</div>
		</div>
	</div>
</div>
<link rel="stylesheet" href="/assets/css/dropzone.css">
<script src="/assets/js/dropzone.min.js"></script>