<div id="create-braille-modal" class="modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger"><i class="ace-icon fa fa-file-pdf-o"></i>&nbsp;Criar PDF para braille</h4>
			</div>

			<div class="modal-body">

				<div class="row">
					<div id="msg"></div>

					<div class="col-xs-12 col-sm-5">

						<ul class="list-unstyled spaced2">
							<li class="text-info"><i class="ace-icon fa fa-angle-right"></i>&nbsp;Nº de Obra: <input type="text" id="create-braille-numobra" class="input-sm"/> <button type="button" class="btn btn-primary btn-minier" onclick="setNewJob()"><i class="ace-icon fa fa-sign-out"></i></button><div id="modal-create-braille-obra-error"></div></li>
							<li class="text-info"><i class="ace-icon fa fa-angle-right"></i>&nbsp;Nº de Peças: <span id="create-braille-numpecas" class="text-black"></span></li>
							<li class="text-info"><i class="ace-icon fa fa-angle-right"></i>&nbsp;Nº de Linhas: <span id="create-braille-numlinhas" class="text-black"></span></li>
							<li class="text-info"><i class="ace-icon fa fa-angle-right"></i>&nbsp;Preço: <span class="text-black">&euro;</span><span id="create-braille-preco" class="text-black"></span></li>
							<li class="text-info"><i class="ace-icon fa fa-angle-right"></i>&nbsp;Texto: <textarea id="create-braille-texto" rows="5" ></textarea></li>

						</ul>




					</div>
					<div class="col-xs-12 col-sm-5">
						<div id="copiado"></div>
						<label for="create-braille-textarea"><i class="ace-icon fa fa-file-text-o"></i>&nbsp;Texto Optimus</label>

						<textarea name="create-braille-textarea" id="create-braille-textarea" rows="13" cols="30"></textarea>



					</div>
				</div>

				<div class="row">

					<div class="col-xs-12">
						<h4 class="blue smaller lighter"><i class="fa fa-picture-o"></i> Representação Gráfica</h4>
						<div id="create-braille-imagem"></div>


					</div>

				</div>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					Fechar
				</button>
				<!--
				<a href="#modal-form-mail-pdf" role="button" class="btn btn-warning btn-sm" data-toggle="modal"> <i class="ace-icon fa fa-envelope"></i>Enviar por email </a>
				-->

				<span id="create-braille-submit"></span>
			</div>
		</div>
	</div>
</div>
