<div class="demo-remove">
<div id="dialog-form-remove" title="Remover Cortante Folha de Obra">
	<p class="validateTips">Todos os campos são obrigatórios..</p>
<form>
	<fieldset>
		<label for="obra-remove">Nº Obra</label>
		<input type="text" name="obra-remove" id="obra-remove" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
</div>
</div>
<script type="text/javascript" src="/js/cortantes/removeoptimus.js"></script>

