<style>
	label, input { display:block; }
		input.text { margin-bottom:12px; width:95%; padding: .4em; }
		fieldset { padding:0; border:0; margin-top:25px; }
		
		div#users-contain { width: 350px; margin: 20px 0; }
		div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
		div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
		.ui-dialog .ui-state-error { padding: .3em; }
		.validateTips { border: 1px solid transparent; padding: 0.3em; }
	</style>


<div class="demo">

<div id="dialog-form" title="Inserir Cortante para Folha de Obra">
	<p class="validateTips">Todos os campos são obrigatórios..</p>

	<form>
	<fieldset>
		<label for="obra">Nº Obra</label>
		<input type="text" name="obra" id="obra" class="text ui-widget-content ui-corner-all" />
		<label for="cortante">Cortante</label>
		<input type="text" name="cortante" id="cortante" value="" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
</div>

</div>
<script type="text/javascript" src="/js/cortantes/optimus.js"></script>