<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
$("#numero").focus();
$("button, input:submit").button();
$("button, input:submit, a", ".check").button();
$("#formato-a").keypress(function (e)  
{if(e.which!=8 && e.which!=0 && e.which!=44 && e.which!=46 && e.which!=13 && (e.which<48 || e.which>57))
{$("#errmsg").html("Apenas números.").show().fadeOut(2000); return false;}});
$("#formato-b").keypress(function (e)  
{if(e.which!=8 && e.which!=0 && e.which!=44 && e.which!=46 && e.which!=13 && (e.which<48 || e.which>57))
{$("#errmsg").html("Apenas números.").show().fadeOut(2000); return false;}});
$("#formato-h").keypress(function (e)  
{if(e.which!=8 && e.which!=0 && e.which!=44 && e.which!=46 && e.which!=13 && (e.which<48 || e.which>57))
{$("#errmsg").html("Apenas números.").show().fadeOut(2000); return false;}});
$("#cortante").keypress(function (e)  
{if(e.which!=8 && e.which!=0 && e.which!=44 && e.which!=46 && e.which!=13 && (e.which<48 || e.which>57))
{$("#errmsg").html("Apenas números.").show().fadeOut(2000); return false;}});
});
</script>