<script type="text/javascript" src="/js/labs/index/script.js"></script>

<div align="center" class="novoregisto"><br />
<table><tr><td>
Insira o Código F3:&nbsp; <input type="text"
	size="15" id="codf3" name="codf3" /> <input type='button'
	onclick='search();' value='Procurar' />
</td><td>Insira o Código Cliente:&nbsp; <input type="text"
	size="15" id="codcliente" name="codcliente" /> <input type='button'
	onclick='search1();' value='Procurar' /></td></tr></table>
	<br />
	<b><a href="#">+ criar novo registo</a></b>
</div>