<div id="<?=$this->job?>" title="Obra N&ordm;<?=$this->job?>">
                <div class="list-prod-summary">
                    <div class="list-prod-info-left">
                    <table>
                        <tr>
                            <td class="list-prod-info-td-tit">Formato:</td>
                            <td class="list-prod-info-td-txt"><?=$this->formato?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">Edi&ccedil;&atilde;o:</td>
                            <td class="list-prod-info-td-txt"><?=$this->edicao?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">Cartolina:</td>
                            <td class="list-prod-info-td-txt"><?=$this->cartolina?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">C&oacute;d. Produto:</td>
                            <td class="list-prod-info-td-txt"><?=$this->codproduto?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">C&oacute;d. F3:</td>
                            <td class="list-prod-info-td-txt"><?=$this->codf3?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">Data Pedida:</td>
                            <td class="list-prod-info-td-txt"><?=$this->datapedida?></td> 
                        </tr>
                        <tr>
                            <td class="list-prod-info-td-tit">Qtd. Pedida:</td>
                            <td class="list-prod-info-td-txt"><?=$this->qtdpedida?></td> 
                        </tr>
                    </table>
                    
                    </div>
                    <div class="list-prod-info-right">
                    <?php if (file_exists("/media/scope/imagens_ricardo/" . $this->codf3 . ".pdf") && ! file_exists("/media/scope/imagens_ricardo/" . $this->codf3 . ".jpg")) :
                            $preview = new App_Files_CreateImages();
                            $preview->setCodF3($this->codf3);
                            $preview->setNumObra($this->job);
                            $preview->convertWithoutRelocation();?>
                            
                     <?php elseif (file_exists("/media/scope/imagens_ricardo/" . substr($this->codf3, 0, -2) . ".pdf") && ! file_exists("/media/scope/imagens_ricardo/" . substr($this->codf3, 0, -2) . ".jpg")) :
                            $preview = new App_Files_CreateImages();
                            $preview->setCodF3($this->codf3);
                            $preview->setNumObra($this->job);
                            $preview->convertWithoutRelocation();?>
                                
                     <?php elseif (file_exists("/media/scope/imagens_ricardo/" . $this->codf3 . ".jpg")) :?>
                         <img src="http://intranet.fterceiro.pt/media/scope/imagens_ricardo/<?=$this->codf3?>.jpg" alt="Thumbnail do Trabalho" />
                     <?php elseif (file_exists("/media/scope/imagens_ricardo/" . substr($this->codf3, 0, -2) . ".jpg")) :?>
                         <img src="http://intranet.fterceiro.pt/media/scope/imagens_ricardo/<?=substr($this->codf3, 0, -2)?>.jpg" alt="Thumbnail do Trabalho" />    
                     <?php else :?>
                        <img src="/imagens/nopreview.png" />
                     <?php endif; ?>    
                    </div>
                </div>
           </div>
           <script type="text/javascript">
            $("#<?=$this->job;?>").dialog({autoOpen: false,height: 550,width: 640,modal: true});
            $("#pp-<?=$this->job;?>").click(function() {$("#<?=$this->job;?>").dialog("open");return false;});
            </script>
            
            