<style>
	
		label, input { display:block; }
		input.text { margin-bottom:12px; width:95%; padding: .4em; }
		fieldset { padding:0; border:0; margin-top:25px; }
		
		div#users-contain { width: 350px; margin: 20px 0; }
		div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
		div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
		.ui-dialog .ui-state-error { padding: .3em; }
		.validateTips { border: 1px solid transparent; padding: 0.3em; }
</style>
<script type="text/javascript" src="/js/cortantes/index/script2.js"></script>



<div class="demo" id="ajax_error_1">

<div id="dialog-cortante" title="Detalhes do Cortante">
	
<table id="the-table-producao-330">
    <tr>
    	<th>Estante</th>
    	<th>C&oacute;digo</th>
    	<th>Cortante</th>
	<tr>
	<tr>
    	<td id="estante"></td>
    	<td id="codigo"></td>
    	<td id="cortan"></td>
	</tr>
</table>
<table id="the-table-producao-330">
    <tr>
    	<th>A</th>
    	<th>B</th>
    	<th>H</th>
    	<th>f</th>
    	<th>g</th>
	<tr>
	<tr>
    	<td id="value_A"></td>
    	<td id="value_B"></td>
    	<td id="value_H"></td>
    	<td id="value_f"></td>
    	<td id="value_g"></td>
	</tr>
</table>
<table id="the-table-producao-330">
    <tr>
    	<th>Pala</th>
    	<th>Tipo</th>
    	<th>Fto. Util</th>
    	<th>Fto. Entr.</th>
    <tr>
	<tr>
    	<td id="value_pala"></td>
    	<td id="value_tipo"></td>
    	<td id="value_util"></td>
    	<td id="value_entrada"></td>
    </tr>
</table>
<table id="the-table-producao-330">
    <tr>
    	<th>Esp</th>
    	<th>Braille</th>
    	<th>Br. Pos.</th>
    	<th>Br. Caract.</th>
    <tr>
	<tr>
    	<td id="value_esp"></td>
    	<td id="value_Braille1"></td>
    	<td id="value_Braille2"></td>
    	<td id="value_Braille3"></td>
    </tr>
</table>
<table id="the-table-producao-330">
    <tr>
    	<th>Fto. Std.</th>
    	<th>Fto. Otm.</th>
    	<th>Descasque</th>
    <tr>
	<tr>
    	<td id="value_fto"></td>
    	<td id="value_otimizado"></td>
    	<td id="value_descasque"></td>
    </tr>
</table>
<table id="the-table-producao-330">
    <tr>
    	<th>Observações</th>
    <tr>
	<tr>
    	<td id="value_obs"></td>
    </tr>
</table>
<div align="center">
<table class="novocortante">
  <tr>
    <td id="editar_cortante"></td>
    <td id="apagar_cortante"></td>
   </tr>
</table>
</div>
</div>
</div>