<div class="light-login">
	<div class="main-container">
		<div class="main-content">
			<div class="row">
				<div class="login-container">
					<div class="center">
						<div class="position-relative">
							<div id="login-box" class="login-box visible widget-box no-border">
								<div class="widget-body">
									<div class="widget-main">
										<h4 class="header blue lighter bigger">
											<i class="ace-icon fa fa-lock green"></i>
											Área Protegida
										</h4>
										<div class="space-12"></div>
										<div class="center blue">Para aceder insira a sua password:</div>
										<div class="space-12"></div>
										<form>
											<fieldset>
												<label class="block clearfix">
													<span class="block input-icon input-icon-right">
														<input type="text" class="form-control" placeholder="Password" id="config-password">
														<i class="ace-icon fa fa-lock"></i>
													</span>
												</label>
												<div class="space-16"></div>
												<div class="clearfix">
													<button type="button" class="width-35 pull-right btn btn-sm btn-primary">
														<i class="ace-icon fa fa-key"></i>
														<span class="bigger-110">Login</span>
													</button>
												</div>
												<div class="space-16"></div>
											</fieldset>
										</form>
									</div><!-- /.widget-main -->
									<div class="toolbar clearfix">
										<div class="space"></div>
									</div>
								</div><!-- /.widget-body -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<style type="text/css">
	.light-login{
		background: none;
	}
</style>