<div class="col-xs-3">
	<div class="widget-box ui-sortable-handle">
		<div class="widget-header"> <h5 class="widget-title">Utilizadores Braille</h5>
			<!-- #section:custom/widget-box.toolbar -->
			<div class="widget-toolbar">
				<a href="#" data-action="collapse"> <i class="ace-icon fa fa-chevron-up"></i> </a>
				<a href="#" data-action="close"> <i class="ace-icon fa fa-times"></i> </a> </div>
			<!-- /section:custom/widget-box.toolbar -->
		</div>
		<div class="widget-body">
			<div class="widget-main">
				<!-- #section:custom/widget-box.body -->
				<?php echo $this->partial('partials/config/arqbrailleusers.phtml', array("names" => $this->names)) ?>
				<!-- /section:custom/widget-box.body -->
			</div>
		</div>
	</div>
</div>