<?php $config = Zend_Registry::get('home_links'); ?>
<table id="main_menu">
<tr>
	<td align="center"><a href="<?=$config->home;?>"> <img src="/images/icons/home.png" height="52px"
		width="56px" alt="Home" style="border: none" /> <br />
	Home </a></td>
	<td align="center"><a href="/<?=$config->selo;?>"> <img src="/images/icons/selo.png" height="52px"
		width="56px" alt="Selo" style="border: none" /> <br />
	Selo </a></td>
	<td align="center"><a href="/<?=$config->emprova;?>"> <img src="/images/icons/emprova.png" height="52px"
		width="56px" alt="Provas" style="border: none" /> <br />
	Em Prova </a></td>
	<td align="center"><a href="/<?=$config->braille;?>"> <img src="/images/icons/braille.png"
		height="52px" width="56px" alt="Braille" style="border: none" /> <br />
	Braille </a></td>
</tr>
<tr>
	<td align="center"><a href="/<?=$config->laetus;?>"> <img src="/images/icons/laetus.png"
		height="52px" width="56px" alt="Braille" style="border: none" /> <br />
	Laetus </a></td>
	<td align="center"><a href="/<?=$config->obras;?>"> <img src="/images/icons/obras.png"
		height="52px" width="56px" alt="Cockpit" style="border: none" /> <br />
	Obras </a></td>
	<td align="center"><a href="/<?=$config->tolerancias;?>"> <img src="/images/icons/tolerancias.png" height="52px"
		width="56px" alt="Toler&acirc;ncias" style="border: none" /> <br />
	Toler&acirc;ncias </a></td>
	<td align="center"><a href="/<?=$config->registos;?>"> <img src="/images/icons/registos.png" height="52px"
		width="56px" alt="Laboratorios" style="border: none" /> <br />
	Registos </a></td>
</tr>
<tr>
	<td align="center"><a href="/<?=$config->arqchapas;?>"> <img src="/images/icons/arq-chapas.png" height="52px"
		width="56px" alt="Arquivo Chapas" style="border: none" /> <br />
	Arq. Chapas</a></td>
	<td align="center"><a href="/<?=$config->chapasrec;?>"> <img src="/images/icons/chapas-rec.png" height="52px"
		width="56px" alt="Chapas " style="border: none" /> <br />
	Chapas Rec.</a></td>
	<td align="center"><a href="/<?=$config->labs;?>"> <img src="/images/icons/labs.png" height="52px"
		width="56px" alt="Labs Home" style="border: none" /> <br />
	Labs </a></td>
	<td align="center"><a href="/<?=$config->cliches;?>"> <img src="/images/icons/cliches.png"
		height="52px" width="56px" alt="Cliches" style="border: none" /> <br />
	Cliches </a></td>
</tr>
<tr>
	<td align="center"><a href="/<?=$config->cortantes;?>"> <img src="/images/icons/cortantes.png"
		height="52px" width="56px" alt="Cortantes" style="border: none" /> <br />
	Cortantes </a></td>
	<td align="center"><a href="/<?=$config->producao;?>"> <img src="/images/icons/producao.png"
		height="52px" width="56px" alt="Produ&ccedil;&atilde;o" style="border: none" /> <br />
	Produ&ccedil;&atilde;o </a></td>
	<td align="center"><a href="/<?=$config->entregas;?>"> <img src="/images/icons/entregas.png"
		height="52px" width="56px" alt="Entregas" style="border: none" /> <br />
	Entregas </a></td>
	<td align="center"><a href="/<?=$config->caixas;?>"> <img src="/images/icons/caixas.png"
		height="52px" width="56px" alt="Caixas" style="border: none" /> <br />
	Caixas </a></td>
</tr>
</table>