<?php $config = Zend_Registry::get('home_links'); ?>




<ul>
	<li><a href="<?=$config->home;?>"> <img src="/images/icons/home.png" height="36px"
		width="36px" alt="Home" style="border: none" /> <br />
	Home </a></li>
	<li><a href="/<?=$config->selo;?>"> <img src="/images/icons/selo.png" height="36px"
		width="36px" alt="Selo" style="border: none" /> <br />
	Selo </a></li>
	<li><a href="/<?=$config->emprova;?>"> <img src="/images/icons/emprova.png" height="36px"
		width="36px" alt="Provas" style="border: none" /> <br />
	Em Prova </a></li>
	<li><a href="/<?=$config->braille;?>"> <img src="/images/icons/braille.png"
		height="36px" width="36px" alt="Braille" style="border: none" /> <br />
	Braille </a></li>
	<li><a href="/<?=$config->laetus;?>"> <img src="/images/icons/laetus.png"
		height="36px" width="36px" alt="Braille" style="border: none" /> <br />
	Laetus </a></li>
	<li><a href="/<?=$config->obras;?>"> <img src="/images/icons/obras.png"
		height="36px" width="36px" alt="Cockpit" style="border: none" /> <br />
	Obras </a></li>
	<li><a href="/<?=$config->tolerancias;?>"> <img src="/images/icons/tolerancias.png" height="36px"
		width="36px" alt="Toler&acirc;ncias" style="border: none" /> <br />
	Toler&acirc;ncias </a></li>
	<li><a href="/<?=$config->registos;?>"> <img src="/images/icons/registos.png" height="36px"
		width="36px" alt="Laboratorios" style="border: none" /> <br />
	Registos </a></li>
	<li><a href="/<?=$config->arqchapas;?>"> <img src="/images/icons/arq-chapas.png" height="36px"
		width="36px" alt="Arquivo Chapas" style="border: none" /> <br />
	Arq. Chapas</a></li>
	<li><a href="/<?=$config->chapasrec;?>"> <img src="/images/icons/chapas-rec.png" height="36px"
		width="36px" alt="Chapas " style="border: none" /> <br />
	Chapas Rec.</a></li>
	<li><a href="/<?=$config->labs;?>"> <img src="/images/icons/labs.png" height="36px"
		width="36px" alt="Labs Home" style="border: none" /> <br />
	Labs </a></li>
	<li><a href="/<?=$config->cliches;?>"> <img src="/images/icons/cliches.png"
		height="36px" width="36px" alt="Cliches" style="border: none" /> <br />
	Cliches </a></li>
	<li><a href="/<?=$config->cortantes;?>"> <img src="/images/icons/cortantes.png"
		height="36px" width="36px" alt="Cortantes" style="border: none" /> <br />
	Cortantes </a></li>
	<li><a href="/<?=$config->producao;?>"> <img src="/images/icons/producao.png"
		height="36px" width="36px" alt="Produ&ccedil;&atilde;o" style="border: none" /> <br />
	Produ&ccedil;&atilde;o </a></li>
	<li><a href="/<?=$config->entregas;?>"> <img src="/images/icons/entregas.png"
		height="36px" width="36px" alt="Entregas" style="border: none" /> <br />
	Entregas </a></li>
</ul>