<div id="panel-menu2">
<div align="center">
<h3 style="color:white;padding-top:8px">F3 Embalagem DB</h3>
<?=$this->partial('logos3.phtml');?>
</div>
</div>
<div id="pa">
<a href="#" id="pane">MENU <span id="menu-toggle-image"><img style="border:none;" src="/images/open.png" /></span></a>
</div>
<script type="text/javascript">

$("#pane").click(function(){
	$('#panel-menu2').slideToggle('slow');
});


</script>